"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    // Après l'hydratation, charger la langue depuis localStorage
    const saved = localStorage.getItem('portfolio-language') as Language;
    if (saved && ['fr', 'en', 'ko'].includes(saved)) {
      setLanguageState(saved);
    }
    setIsHydrated(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('portfolio-language', lang);
    }
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      projects: 'Projets',
      contact: 'Contact',
      resume: 'CV',
      socials: 'Réseaux',
      more: 'Plus',
      language: 'Langue',
      theme: 'Thème',
      theme_light: 'Clair',
      theme_dark: 'Sombre',
      select_theme: 'Sélectionner le thème',
      accent: 'Couleur d\'accent',
      select_color: 'Sélectionner la couleur',
    },
    home: {
      greeting: 'Salut! Je suis',
      intro: 'Je suis actuellement',
      student: 'Étudiant',
      student_it: 'Étudiant en Informatique',
      at: 'à',
      passionate: 'Passionné par le développement plus principalement du web et du devops et les technologies modernes.',
      about_me: 'Plus à propos de moi',
    },
    featured: {
      title: 'Projets Vedettes',
      view_all: 'Voir tous',
      no_image: 'Pas d\'image',
    },
    guide: {
      title: 'Guide du Portfolio',
      discover: 'Découvrir les fonctionnalités',
      keyboard_nav: 'Navigation au Clavier',
      keyboard_desc: 'Appuyez sur Espace pour éditer la route dans le breadcrumb',
      keyboard_tip: 'Utilisez Tab pour naviguer entre les suggestions, Enter pour valider',
      themes: 'Système de Thèmes',
      themes_desc: 'Changez le thème via le sélecteur en bas à droite',
      themes_tip: '2 thèmes Catppuccin avec une couleur d\'accent orange cohérente !',
      projects: 'Projets Interactifs',
      projects_desc: 'Cliquez sur un projet pour voir des animations fluides',
      projects_tip: 'Les images et titres se transforment en douceur grâce aux View Transitions',
      commits: 'Commits GitHub',
      commits_desc: 'Les commits récents sont mis en cache pour 30 minutes',
      commits_tip: 'Évite les limites de l\'API GitHub (60 requêtes/heure)',
      game: 'Jeu 2048',
      game_desc: 'Jouez au 2048 directement sur la page d\'accueil !',
      game_tip: 'Utilisez les flèches du clavier, score sauvegardé localement',
      previous: 'Précédent',
      next: 'Suivant',
      finish: 'Terminer',
      tip: 'Astuce',
    },
    about: {
      title: 'À propos de moi',
      greeting: 'Salut!',
      intro_1: 'Je m\'appelle Nathan FERRE',
      intro_2: '— Étudiant en Informatique.',
      intro_3: 'J\'aime créer des',
      interesting_projects: 'projets intéressants',
      intro_4: 'quand j\'ai du temps libre et apprendre de nouvelles choses pas forcément qu\'en informatique.',
      currently: 'Actuellement étudiant à',
      studying: ', je prépare un bachelor en infrastructure pour ensuite me diriger vers un master en infrastructure.',
      outside: 'En dehors de mes cours, j\'aime passer du temps à faire du sport, jouer au tennis et lire des livres. Mais aussi réaliser des projets personnels en développement web et en devops et passer du temps avec mon chat, Luigi',
      see_below: '(voir ci-dessous)',
      and_gaming: '. Et bien entendu jouer aux jeux vidéo (plutôt des jeux solo d\'aventure ou d\'exploration)',
      cat_title: 'Mon Chat (Luigi) !',
      cat_desc: 'Mon chat est',
      cat_horrible: 'horrible',
      cat_desc_2: '. Il adore faire des siestes très longues dans des positions les unes plus étranges que les autres et explorer',
      everything: 'tout',
      cat_desc_3: 'ce qui l\'entoure et essayer de chasser tout ce qui l\'entoure aussi.',
    },
    commits: {
      title: 'Commits Récents',
      loading: 'Chargement des commits...',
      profile: 'profil',
    },
    breadcrumb: {
      routes_found: 'route',
      routes_found_plural: 'routes',
      found: 'trouvée',
      found_plural: 'trouvées',
      tab_help: 'Tab pour naviguer, Enter pour valider',
    },
    location: {
      based_in: 'Actuellement basée sur Toulouse 📍',
      loading_map: 'Chargement de la carte...',
    },
    experience: {
      title: 'Parcours Académique',
      past: 'Passé',
      present: 'Présent',
      current: 'Actuel',
      visit_website: 'Visiter le site web',
      ynov_role: 'Étudiant en Informatique',
      ynov_details: 'Formation en développement web et logiciel.',
    },
    game2048: {
      title: '2048',
      new_game: 'Nouvelle Partie',
      score: 'SCORE',
      best: 'MEILLEUR',
      you_win: '🎉 Vous avez gagné!',
      you_reached: 'Vous avez atteint 2048!',
      keep_playing: 'Continuer à jouer',
      game_over: 'Partie terminée!',
      final_score: 'Score final',
      try_again: 'Réessayer',
      instructions: 'Utilisez les flèches pour déplacer les tuiles. Fusionnez-les pour atteindre 2048!',
      full_version: 'Version complète avec Leaderboard',
      maintenance_title: 'Jeu en maintenance',
      maintenance_desc: 'Le serveur du jeu 2048 n\'est pas disponible actuellement. Veuillez réessayer plus tard.',
      retry: 'Réessayer',
      leaderboard: 'Meilleurs scores',
      play_now: 'Jouer maintenant',
    },
    projects: {
      title: 'Projets',
      description: 'Une sélection de mes projets personnels, académiques et professionnels.',
      all: 'Tous',
      filter: 'Filtrer par',
      loading: 'Chargement...',
      not_found: 'Projet introuvable',
      back: 'Retour aux projets',
      the_project: 'Le Projet',
      tech_stack: 'Pile Technologique',
      features: 'Fonctionnalités',
      conclusion: 'Conclusion',
      search_placeholder: 'Rechercher un projet...',
      sort_label: 'Trier les projets',
      sort_default: 'Par défaut',
      sort_name: 'Par nom (A-Z)',
      sort_date: 'Plus récents',
      quick_filters: 'Filtres rapides (technologies)',
      show_filters: 'Afficher les filtres rapides',
      hide_filters: 'Masquer les filtres rapides',
      all_projects: 'Tous',
      filter_by: 'Filtrer par',
      results_found: 'projet(s) trouvé(s)',
      reset_filters: 'Réinitialiser',
      no_results: 'Aucun projet trouvé pour ce tag',
    },
    socials: {
      title: 'Mes Réseaux Sociaux',
      description: 'Retrouvez-moi sur ces différentes plateformes',
      github_desc: 'Découvrez mes projets open-source et contributions',
      linkedin_desc: 'Connectez-vous avec moi professionnellement',
      email_academic: 'Email Académique',
    },
    skills: {
      title: 'Hardskills',
      level: 'Niveau',
      beginner: 'Débutant',
      intermediate: 'Intermédiaire',
      advanced: 'Avancé',
      expert: 'Expert',
      frontend: 'Frontend',
      backend: 'Backend',
      tools: 'Outils',
      languages: 'Langages',
    },
    contact: {
      title: 'Me Contacter',
      description: 'N\'hésitez pas à me contacter pour toute question ou collaboration',
      form_title: 'Formulaire de Contact',
      name_label: 'Nom',
      name_placeholder: 'Votre nom',
      email_label: 'Email',
      email_placeholder: 'votre.email@exemple.com',
      subject_label: 'Sujet',
      subject_placeholder: 'Objet de votre message',
      message_label: 'Message',
      message_placeholder: 'Votre message...',
      send_button: 'Envoyer',
      sending: 'Envoi en cours...',
      success: 'Message envoyé avec succès!',
      error: 'Erreur lors de l\'envoi du message',
      required: 'Ce champ est requis',
      invalid_email: 'Email invalide',
      alternative_title: 'Autres moyens de me contacter',
      my_socials: 'Mes réseaux',
      github_link: 'GitHub',
      linkedin_link: 'LinkedIn',
      email_direct: 'Email direct',
    },
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      contact: 'Contact',
      resume: 'Resume',
      socials: 'Socials',
      more: 'More',
      language: 'Language',
      theme: 'Theme',
      theme_light: 'Light',
      theme_dark: 'Dark',
      select_theme: 'Select theme',
      accent: 'Accent Color',
      select_color: 'Select color',
    },
    home: {
      greeting: 'Hey! I\'m',
      intro: 'I am currently',
      student: 'Student',
      student_it: 'Computer Science Student',
      at: 'at',
      passionate: 'Passionate about devops and web development and modern technologies.',
      about_me: 'More about me',
    },
    featured: {
      title: 'Featured Projects',
      view_all: 'View all',
      no_image: 'No image',
    },
    guide: {
      title: 'Portfolio Guide',
      discover: 'Discover features',
      keyboard_nav: 'Keyboard Navigation',
      keyboard_desc: 'Press Space to edit the route in the breadcrumb',
      keyboard_tip: 'Use Tab to navigate suggestions, Enter to validate',
      themes: 'Theme System',
      themes_desc: 'Change the theme via the selector at the bottom right',
      themes_tip: '2 Catppuccin themes with a consistent orange accent color!',
      projects: 'Interactive Projects',
      projects_desc: 'Click on a project to see smooth animations',
      projects_tip: 'Images and titles transform smoothly thanks to View Transitions',
      commits: 'GitHub Commits',
      commits_desc: 'Recent commits are cached for 30 minutes',
      commits_tip: 'Avoids GitHub API limits (60 requests/hour)',
      game: '2048 Game',
      game_desc: 'Play 2048 directly on the homepage!',
      game_tip: 'Use arrow keys, score saved locally',
      previous: 'Previous',
      next: 'Next',
      finish: 'Finish',
      tip: 'Tip',
    },
    about: {
      title: 'About Me',
      greeting: 'Hey!',
      intro_1: 'My name is Nathan FERRE',
      intro_2: '— Computer Science Student.',
      intro_3: 'I love creating',
      interesting_projects: 'interesting projects',
      intro_4: 'when I have free time and learning new things not necessarily only in computer science.',
      currently: 'Currently studying at',
      studying: ', I am preparing a bachelor\'s degree in infrastructure to then move towards a master\'s degree in infrastructure.',
      outside: 'Outside of my classes, I like to spend time exercising, playing tennis and reading books. But also working on personal projects in web development and devops and spending time with my cat, Luigi',
      see_below: '(see below)',
      and_gaming: '. And of course playing video games (mostly solo adventure or exploration games)',
      cat_title: 'My Cat (Luigi)!',
      cat_desc: 'My cat is',
      cat_horrible: 'terrible',
      cat_desc_2: '. He loves taking very long naps in increasingly strange positions and exploring',
      everything: 'everything',
      cat_desc_3: 'around him and trying to hunt everything around him too.',
    },
    commits: {
      title: 'Recent Commits',
      loading: 'Loading commits...',
      profile: 'profile',
    },
    breadcrumb: {
      routes_found: 'route',
      routes_found_plural: 'routes',
      found: 'found',
      found_plural: 'found',
      tab_help: 'Tab to navigate, Enter to confirm',
    },
    location: {
      based_in: 'Currently based in Toulouse 📍',
      loading_map: 'Loading map...',
    },
    experience: {
      title: 'Academic Background',
      past: 'Past',
      present: 'Present',
      current: 'Current',
      visit_website: 'Visit website',
      ynov_role: 'Computer Science Student',
      ynov_details: 'Training in web and software development.',
    },
    game2048: {
      title: '2048',
      new_game: 'New Game',
      score: 'SCORE',
      best: 'BEST',
      you_win: '🎉 You Win!',
      you_reached: 'You reached 2048!',
      keep_playing: 'Keep Playing',
      game_over: 'Game Over!',
      final_score: 'Final Score',
      try_again: 'Try Again',
      instructions: 'Use arrow keys to move tiles. Merge tiles to reach 2048!',
      full_version: 'Full version with Leaderboard',
      maintenance_title: 'Game under maintenance',
      maintenance_desc: 'The 2048 game server is currently unavailable. Please try again later.',
      retry: 'Retry',
      leaderboard: 'Top scores',
      play_now: 'Play now',
    },
    projects: {
      title: 'Projects',
      description: 'A selection of my personal, academic and professional projects.',
      all: 'All',
      filter: 'Filter by',
      loading: 'Loading...',
      not_found: 'Project not found',
      back: 'Back to projects',
      the_project: 'The Project',
      tech_stack: 'Tech Stack',
      features: 'Features',
      conclusion: 'Conclusion',
      search_placeholder: 'Search for a project...',
      sort_label: 'Sort projects',
      sort_default: 'Default',
      sort_name: 'By name (A-Z)',
      sort_date: 'Most recent',
      quick_filters: 'Quick filters (technologies)',
      show_filters: 'Show quick filters',
      hide_filters: 'Hide quick filters',
      all_projects: 'All',
      filter_by: 'Filter by',
      results_found: 'project(s) found',
      reset_filters: 'Reset',
      no_results: 'No project found for this tag',
    },
    socials: {
      title: 'My Social Networks',
      description: 'Find me on these different platforms',
      github_desc: 'Discover my open-source projects and contributions',
      linkedin_desc: 'Connect with me professionally',
      email_academic: 'Academic Email',
    },
    skills: {
      title: 'Hardskills',
      level: 'Level',
      beginner: 'Beginner',
      intermediate: 'Intermediate',
      advanced: 'Advanced',
      expert: 'Expert',
      frontend: 'Frontend',
      backend: 'Backend',
      tools: 'Tools',
      languages: 'Languages',
    },
    contact: {
      title: 'Contact Me',
      description: 'Feel free to reach out for any questions or collaborations',
      form_title: 'Contact Form',
      name_label: 'Name',
      name_placeholder: 'Your name',
      email_label: 'Email',
      email_placeholder: 'your.email@example.com',
      subject_label: 'Subject',
      subject_placeholder: 'Message subject',
      message_label: 'Message',
      message_placeholder: 'Your message...',
      send_button: 'Send',
      sending: 'Sending...',
      success: 'Message sent successfully!',
      error: 'Error sending message',
      required: 'This field is required',
      invalid_email: 'Invalid email',
      alternative_title: 'Other ways to reach me',
      my_socials: 'My socials',
      github_link: 'GitHub',
      linkedin_link: 'LinkedIn',
      email_direct: 'Direct email',
    },
  },
  ko: {
    nav: {
      home: '홈',
      about: '소개',
      projects: '프로젝트',
      contact: '연락처',
      resume: '이력서',
      socials: '소셜',
      more: '더보기',
      language: '언어',
      theme: '테마',
      theme_light: '라이트',
      theme_dark: '다크',
      select_theme: '테마 선택',
      accent: '강조 색상',
      select_color: '색상 선택',
    },
    home: {
      greeting: '안녕하세요! 저는',
      intro: '현재',
      student: '학생',
      student_it: '컴퓨터 과학 학생',
      at: '입니다',
      passionate: '웹 개발과 현대 기술에 열정적입니다.',
      about_me: '더 알아보기',
    },
    featured: {
      title: '주요 프로젝트',
      view_all: '모두 보기',
      no_image: '이미지 없음',
    },
    guide: {
      title: '포트폴리오 가이드',
      discover: '기능 알아보기',
      keyboard_nav: '키보드 탐색',
      keyboard_desc: '스페이스를 눌러 경로를 편집하세요',
      keyboard_tip: 'Tab으로 제안 탐색, Enter로 확인',
      themes: '테마 시스템',
      themes_desc: '오른쪽 하단의 선택기를 통해 테마 변경',
      themes_tip: '일관된 주황색 강조 색상을 가진 2개 Catppuccin 테마!',
      projects: '인터랙티브 프로젝트',
      projects_desc: '프로젝트를 클릭하여 부드러운 애니메이션 보기',
      projects_tip: 'View Transitions로 이미지와 제목이 부드럽게 변환됩니다',
      commits: 'GitHub 커밋',
      commits_desc: '최근 커밋이 30분 동안 캐시됩니다',
      commits_tip: 'GitHub API 제한 회피 (시간당 60개 요청)',
      game: '2048 게임',
      game_desc: '홈페이지에서 직접 2048 플레이!',
      game_tip: '화살표 키 사용, 점수는 로컬에 저장',
      previous: '이전',
      next: '다음',
      finish: '완료',
      tip: '팁',
    },
    about: {
      title: '소개',
      greeting: '안녕하세요!',
      intro_1: '제 이름은 Nathan FERRE입니다',
      intro_2: '— 주니어 개발자.',
      intro_3: '저는',
      interesting_projects: '흥미로운 프로젝트',
      intro_4: '를 만드는 것을 좋아하며 여가 시간에 컴퓨터 과학뿐만 아니라 새로운 것을 배우는 것을 좋아합니다.',
      currently: '현재',
      studying: '에서 공부하고 있으며, 개발 학사 학위를 준비한 후 풀스택 개발 석사 과정으로 나아갈 계획입니다.',
      outside: '수업 외에는 운동하고, 테니스를 치고, 책을 읽는 것을 좋아합니다. 또한 웹 개발과 데브옵스의 개인 프로젝트를 진행하고, 고양이 Luigi와 시간을 보냅니다',
      see_below: '(아래 참조)',
      and_gaming: '. 그리고 물론 비디오 게임(주로 솔로 어드벤처나 탐험 게임)을 즐깁니다',
      cat_title: '내 고양이 (Luigi)!',
      cat_desc: '내 고양이는',
      cat_horrible: '끔찍합니다',
      cat_desc_2: '. 그는 점점 더 이상한 자세로 아주 긴 낮잠을 자는 것을 좋아하고',
      everything: '모든 것',
      cat_desc_3: '을 탐험하고 주변의 모든 것을 사냥하려고 합니다.',
    },
    commits: {
      title: '최근 커밋',
      loading: '커밋 로딩 중...',
      profile: '프로필',
    },
    breadcrumb: {
      routes_found: '경로',
      routes_found_plural: '경로',
      found: '발견됨',
      found_plural: '발견됨',
      tab_help: 'Tab으로 탐색, Enter로 확인',
    },
    location: {
      based_in: '현재 툴루즈에 거주 중 📍',
      loading_map: '지도 로딩 중...',
    },
    experience: {
      title: '학업 배경',
      past: '과거',
      present: '현재',
      current: '현재',
      visit_website: '웹사이트 방문',
      ynov_role: '컴퓨터 과학 학생',
      ynov_details: '웹 및 소프트웨어 개발 교육.',
    },
    game2048: {
      title: '2048',
      new_game: '새 게임',
      score: '점수',
      best: '최고',
      you_win: '🎉 승리!',
      you_reached: '2048에 도달했습니다!',
      keep_playing: '계속 플레이',
      game_over: '게임 오버!',
      final_score: '최종 점수',
      try_again: '다시 시도',
      instructions: '화살표 키로 타일을 이동하세요. 타일을 합쳐 2048에 도달하세요!',
      full_version: '리더보드가 있는 전체 버전',
      maintenance_title: '게임 점검 중',
      maintenance_desc: '2048 게임 서버를 현재 사용할 수 없습니다. 나중에 다시 시도해 주세요.',
      retry: '다시 시도',
      leaderboard: '최고 점수',
      play_now: '지금 플레이',
    },
    projects: {
      title: '프로젝트',
      description: '개인, 학술 및 전문 프로젝트 모음',
      all: '모두',
      filter: '필터',
      loading: '로딩 중...',
      not_found: '프로젝트를 찾을 수 없습니다',
      back: '프로젝트로 돌아가기',
      the_project: '프로젝트',
      tech_stack: '기술 스택',
      features: '기능',
      conclusion: '결론',
      search_placeholder: '프로젝트 검색...',
      sort_label: '프로젝트 정렬',
      sort_default: '기본',
      sort_name: '이름순 (A-Z)',
      sort_date: '최신순',
      quick_filters: '빠른 필터 (기술)',
      show_filters: '빠른 필터 표시',
      hide_filters: '빠른 필터 숨기기',
      all_projects: '모두',
      filter_by: '필터',
      results_found: '프로젝트를 찾았습니다',
      reset_filters: '초기화',
      no_results: '이 태그에 대한 프로젝트가 없습니다',
    },
    socials: {
      title: '소셜 네트워크',
      description: '다양한 플랫폼에서 저를 찾아보세요',
      github_desc: '오픈소스 프로젝트 및 기여 확인',
      linkedin_desc: '전문적으로 연결하기',
      email_academic: '학교 이메일',
    },
    skills: {
      title: 'Hardskills',
      level: '수준',
      beginner: '초보',
      intermediate: '중급',
      advanced: '고급',
      expert: '전문가',
      frontend: '프론트엔드',
      backend: '백엔드',
      tools: '도구',
      languages: '언어',
    },
    contact: {
      title: '연락하기',
      description: '질문이나 협업을 위해 언제든지 연락주세요',
      form_title: '연락 양식',
      name_label: '이름',
      name_placeholder: '이름',
      email_label: '이메일',
      email_placeholder: 'your.email@example.com',
      subject_label: '제목',
      subject_placeholder: '메시지 제목',
      message_label: '메시지',
      message_placeholder: '메시지를 입력하세요...',
      send_button: '보내기',
      sending: '전송 중...',
      success: '메시지가 성공적으로 전송되었습니다!',
      error: '메시지 전송 중 오류가 발생했습니다',
      required: '이 필드는 필수입니다',
      invalid_email: '유효하지 않은 이메일',
      alternative_title: '다른 연락 방법',
      my_socials: '내 소셜',
      github_link: 'GitHub',
      linkedin_link: 'LinkedIn',
      email_direct: '직접 이메일',
    },
  },
};
